"""Command scanner — blocks dangerous terminal commands.

This is the first safety gate. Every command generated by NeuroBridge
goes through this scanner before execution. No exceptions.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any

from neuro.constants import BLOCKED_COMMANDS, BLOCKED_PATHS


@dataclass
class ScanResult:
    """Result of scanning a command."""

    command: str
    safe: bool
    violations: list[str] = field(default_factory=list)
    severity: str = "none"  # "none", "warning", "critical"


# ── Pattern-based rules ────────────────────────────────────────────────────────

# Critical: immediate block, no override
CRITICAL_PATTERNS = [
    (r"\brm\s+-rf\s+/\s*$", "rm -rf / — would destroy entire filesystem"),
    (r"\brm\s+-rf\s+~/?\s*$", "rm -rf ~ — would destroy home directory"),
    (r"\brm\s+-rf\s+\*", "rm -rf * — recursive wildcard delete"),
    (r"\bmkfs\b", "mkfs — would format a disk"),
    (r"\bdd\s+if=", "dd — raw disk write"),
    (r"\bchmod\s+-R\s+777\s+/", "chmod -R 777 / — permission escalation on root"),
    (r">\s*/dev/sd[a-z]", "direct write to block device"),
    (r"\b:(){ :\|:& };:", "fork bomb"),
]

# Warning: allowed with approval
WARNING_PATTERNS = [
    (r"\bsudo\b", "sudo — elevated privileges requested"),
    (r"\bcurl\b.*\|\s*(ba)?sh", "curl | sh — remote code execution"),
    (r"\bwget\b.*\|\s*(ba)?sh", "wget | sh — remote code execution"),
    (r"\beval\b", "eval — dynamic code execution"),
    (r"\bchmod\s+-R\s+777", "chmod -R 777 — broad permission change"),
    (r"\brm\s+-rf\b", "rm -rf — recursive force delete"),
    (r"\bgit\s+push\s+.*--force", "git push --force — destructive push"),
    (r"\bgit\s+reset\s+--hard", "git reset --hard — destructive reset"),
    (r"\bdrop\s+database\b", "DROP DATABASE — destructive SQL"),
    (r"\bdrop\s+table\b", "DROP TABLE — destructive SQL"),
    (r"\btruncate\s+table\b", "TRUNCATE TABLE — destructive SQL"),
]

# Path access rules
BLOCKED_PATH_PATTERNS = [
    (r"~/.ssh", "SSH keys access"),
    (r"/\.ssh/", "SSH keys access"),
    (r"\.env\b", ".env file access (may contain secrets)"),
    (r"~/.aws", "AWS credentials access"),
    (r"~/.gcloud", "GCloud credentials access"),
    (r"~/.config/gcloud", "GCloud credentials access"),
    (r"/etc/shadow", "password file access"),
    (r"/etc/passwd", "user database access"),
    (r"~/.kube/config", "Kubernetes credentials"),
    (r"~/.docker/config", "Docker credentials"),
]


def scan_command(command: str) -> ScanResult:
    """Scan a command for safety violations.

    Returns a ScanResult indicating if the command is safe to execute.
    """
    violations: list[str] = []
    severity = "none"

    cmd = command.strip()
    if not cmd:
        return ScanResult(command=command, safe=True)

    # ── Critical patterns (always blocked) ─────────────────────────────────
    for pattern, description in CRITICAL_PATTERNS:
        if re.search(pattern, cmd, re.IGNORECASE):
            violations.append(f"🔴 CRITICAL: {description}")
            severity = "critical"

    # ── Warning patterns (require approval) ────────────────────────────────
    for pattern, description in WARNING_PATTERNS:
        if re.search(pattern, cmd, re.IGNORECASE):
            violations.append(f"🟡 WARNING: {description}")
            if severity != "critical":
                severity = "warning"

    # ── Blocked path access ────────────────────────────────────────────────
    for pattern, description in BLOCKED_PATH_PATTERNS:
        if re.search(pattern, cmd, re.IGNORECASE):
            violations.append(f"🔴 PATH: {description}")
            severity = "critical"

    # ── Pipe chains (check each segment) ───────────────────────────────────
    if "|" in cmd:
        segments = cmd.split("|")
        for i, seg in enumerate(segments[1:], 1):
            seg = seg.strip()
            if seg.startswith("sh") or seg.startswith("bash"):
                violations.append(f"🟡 PIPE: piping to shell (segment {i})")
                if severity != "critical":
                    severity = "warning"

    safe = severity != "critical"
    return ScanResult(
        command=command,
        safe=safe,
        violations=violations,
        severity=severity,
    )


def scan_commands(commands: list[str]) -> list[ScanResult]:
    """Scan multiple commands. Returns list of results."""
    return [scan_command(cmd) for cmd in commands]


def is_safe(command: str) -> bool:
    """Quick check — is this command safe to execute?"""
    return scan_command(command).safe
